ALTER TABLE `go2nurse_service_category` CHANGE COLUMN `id` `id` BIGINT(64) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `go2nurse_service_item` CHANGE COLUMN `id` `id` BIGINT(64) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `go2nurse_service_order` CHANGE COLUMN `id` `id` BIGINT(64) NOT NULL AUTO_INCREMENT ;